# Generated by Django 3.1.1 on 2020-09-13 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('dateBorn', models.DateField(default=datetime.date(2020, 9, 13))),
                ('dateIngress', models.DateField(default=datetime.date(2020, 9, 13))),
            ],
        ),
    ]
