# Generated by Django 3.1.1 on 2020-09-16 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcroDB', '0002_auto_20200914_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dateBorn',
            field=models.DateField(default=datetime.date(2020, 9, 16)),
        ),
        migrations.AlterField(
            model_name='member',
            name='dateIngress',
            field=models.DateField(default=datetime.date(2020, 9, 16)),
        ),
    ]
